name: AlsBanker
version: 0.11
main: com.alexander.alsbanker.AlsBanker
api-version: 1.20
author: SkellyHunter22
description: Full loan scheduler replacement for EcoXpert with Discord integration.
softdepend: [Vault, PlaceholderAPI, PlugManX, PlugMan]
loadbefore: [EcoXpert]

commands:
  loanscheduler:
    description: Admin controls
    permission: alsbanker.admin

  loan:
    description: Request or repay a loan
    usage: "/loan <request|pay|info> [amount]"
    permission: alsbanker.user

  linkdiscord:
    description: Link your Discord account
    usage: "/linkdiscord [discordID]"
    permission: alsbanker.user

  unlinkdiscord:
    description: Unlink your Discord account
    permission: alsbanker.user

  savings:
    description: Manage your savings account
    usage: "/savings <deposit|withdraw|info> [amount]"
    permission: alsbanker.user

  stocks:
    description: Buy and sell stocks
    usage: "/stocks <list|buy|sell|portfolio> [symbol] [shares]"
    permission: alsbanker.user

  steal:
    description: Attempt to pickpocket another player
    usage: "/steal <player>"
    permission: alsbanker.steal

  creditcard:
    description: Apply for and manage a revolving credit card
    usage: "/creditcard <apply|info|charge|pay> [amount]"
    permission: alsbanker.user

permissions:
  alsbanker.admin:
    default: op
  alsbanker.user:
    default: true
  alsbanker.steal:
    default: true
